# Generated by Django 5.2.3 on 2025-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmetadata',
            name='file_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
